sink("./A2D_ACD_bidir.bed.count.bed.A2DACDnascent.Rout")
library( DESeq )
data <- read.delim("./A2D_ACD_bidir.bed.count.bed", sep="\t", header=TRUE)
countsTable <- subset(data, select=c(5,6))
rownames(countsTable) <- data$name
conds <- c("A2C", "ACC")
cds <- newCountDataSet( countsTable, conds )
cds <- estimateSizeFactors( cds )
sizeFactors(cds)
cds <- estimateDispersions( cds, method='blind', sharingMode='fit-only' )
res <- nbinomTest( cds, "A2C", "ACC" )
plotDE <- function( res ) plot(res$baseMean,res$log2FoldChange, log="x", pch=20, cex=.1, col = ifelse( res$padj < .1, "red", "black" ) )
png('./A2D_ACD_bidir.bed.count.bed.A2DACDnascent.png')
plotDE( res )
dev.off()
resSig <- res[ res$padj < .1, ]
write.table(res, file = "./A2D_ACD_bidir.bed.count.bed.A2DACDnascent.res.txt", append = FALSE, sep = "\t")
write.table(resSig, file = "./A2D_ACD_bidir.bed.count.bed.A2DACDnascent.resSig.txt", append = FALSE, sep = "\t")
write.table(resSig[ order(resSig$pval), ], file = "./A2D_ACD_bidir.bed.count.bed.A2DACDnascent.resSig_pvalue.txt", append = FALSE, sep = "\t")
sink()
